name: Build-golang-opencv
on:
  workflow_dispatch:
    inputs:
      golang:
        description: 'golang version (ex: 1.23.3)'
        required: true
        default: '1.23.3'
      opencv:
        description: 'opencv version (ex: 4.10.0)'
        required: true
        default: '4.10.0'

jobs:
  build-arm64:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: GOLANG_VERSION=${{ github.event.inputs.golang }} OPENCV_VERSION=${{ github.event.inputs.opencv }} ./github/build-golang-arm64.sh
  build-amd64:
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: GOLANG_VERSION=${{ github.event.inputs.golang }} OPENCV_VERSION=${{ github.event.inputs.opencv }} ./github/build-golang-amd64.sh
  build-manifest:
    runs-on: [self-hosted, linux, X64]
    needs: [build-arm64, build-amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build manifest
        run: GOLANG_VERSION=${{ github.event.inputs.golang }} OPENCV_VERSION=${{ github.event.inputs.opencv }} ./github/build-golang-manifest.sh
